GET http://localhost:8095/rules/version

###

POST http://localhost:8095/rules/evaluate
Content-Type: application/json

{
    "ruleGroupName": "Por resolver",
    "context": {
        "accept": 1,
        "email": "email"

    }
}

###

POST http://localhost:8095/rules/evaluate-and-fire
Content-Type: application/json

{
  "ruleGroupName": "Por resolver",
  "context": {
    "accept": 1,
    "email": "email"

  }
}
