GET http://localhost:8095/rules/version

###

POST http://localhost:8095/rules/evaluate
Content-Type: application/json

{
    "ruleGroupName": "Por resolver",
    "context": {
        "accept": 12,
        "email": "email"

    }
}

###

